### ISSUE TITLE
Plugin fails to load for some users

### ISSUE THREAD

**Issue by haboutnnah** [YMIndustries/AutoKnight#5] opened 2015-04-10 00:47 UTC
http://i.imgur.com/CeUrQUp.png No  options :(

tried restarting chrome

**Comment by YoshiWalsh** [comment] 2015-04-10 00:48
Could you please go to /r/thebutton, press F12 and see if there are any errors in the Console tab?

**Comment by tf2manu994** [comment] 2015-04-10 02:00
Shine reddit content handler running.
chrome-extension://hjndgefhmfcgpoocjcgoemphhdkbhipm/pageOverlay.js:112 Shine page overlay loaded.
2thebutton:1Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)
https://pixel.redditmedia.com/pixel/of_destiny.png?v=iciPhHaY6iPRf7KDNCF6vy…NhfL74UXC%2Fo2qxkW52tr2Vadd5TLMJkbhpJr5CtWmVSLfsnqxHJkgqYC0Ikk&r=447815990 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://ssl.google-analytics.com/ga.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://www.google-analytics.com/analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://static.adzerk.net/reddit/ads.html?sr=thebutton,loggedin&bust2#https://www.reddit.com Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://pixel.redditmedia.com/pixel/of_defenestration.png?hash=adblock0e31bc319d5b5882b0cddf147f4ce1da5ac9c731&id=adblock&random=4184524989686906.5 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js:30664 Download the React DevTools for a better development experience: http://fb.me/react-devtools
(program):1 LastPass: Skipping form because submit is not a function!
chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/bundle.js:122 Object

**Comment by haboutnnah** [comment] 2015-04-10 02:01
http://i.imgur.com/x1wN23a.png

**Comment by YoshiWalsh** [comment] 2015-04-10 02:59
I don't see any relevant errors in there, I suspect it's a plugin conflict. Could you try disabling all other plugins and see if that fixes it? What if you disable all other Reddit-related plugins? If you can narrow it down to one incompatible plugin then I can try to find a fix.

**Comment by haboutnnah** [comment] 2015-04-10 03:10
Disabled all other plugins, cleared cookies

Still nothin

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) 

is the only thingo in the log

**Comment by YoshiWalsh** [comment] 2015-04-10 03:15
If you go the Sources tab in F12 and then to the Content Scripts tab in the left pane, does AutoKnight show up? It should have foreground.js under it.

![foreground.js](http://i.imgur.com/ollgiqZ.png)

If you go back to the Sources tab in the left pane, under one of the random strings of letters and numbers is there a pagescript.js?

![pagescript.js](http://i.imgur.com/ZSSGAl9.png)

**Comment by haboutnnah** [comment] 2015-04-10 04:13
http://i.imgur.com/yjgwl3y.png
http://i.imgur.com/8QkXBt2.png

**Comment by YoshiWalsh** [comment] 2015-04-10 04:14
This is going to sound silly, but are you sure AutoKnight is installed and enabled? What version do you have? It looks like it's completely not running in any way.

**Comment by haboutnnah** [comment] 2015-04-10 04:43
yup

http://i.imgur.com/324apZU.png

**Comment by YoshiWalsh** [comment] 2015-04-10 04:49
Could you try deleting and re-installing the plugin?

Sorry it's not working for you, I really have no clue what the problem is. It's not even running my code so I don't see anything I can do to fix it.

**Comment by haboutnnah** [comment] 2015-04-10 04:53
Reinstalled, still not working. :(

Could you try uploading the extension so I can see if adding through dev
tools would work?

**Comment by YoshiWalsh** [comment] 2015-04-10 04:56
You can download the entire source of the plugin here: https://github.com/YMIndustries/AutoKnight/archive/master.zip

Extract it somewhere safe and use "Load unpacked extension..." in the Developer Mode section of Extensions. Good luck!

**Comment by haboutnnah** [comment] 2015-04-10 05:29
Still not working :(

**Comment by YoshiWalsh** [comment] 2015-04-10 05:46
What version of Chrome are you using? What Operating System are you using?

**Comment by haboutnnah** [comment] 2015-04-10 07:01
Win8.1 

GoogleChrome Version 41.0.2272.118 m

**Comment by YoshiWalsh** [comment] 2015-04-10 11:06
Oh wait, I might know the issue. What is the full address that you are using to access /r/thebutton?

**Comment by haboutnnah** [comment] 2015-04-10 12:18
https://www.reddit.com/r/thebutton

**Comment by YoshiWalsh** [comment] 2015-04-10 12:48
Yep, that's the issue. We don't currently support HTTPS. I'll get a fix in but until then you can access /r/thebutton over regular HTTP and it should work. Sorry for the inconvenience!

**Comment by YoshiWalsh** [comment] 2015-04-10 12:50
Moving to Issue #8.

**Comment by YoshiWalsh** [comment] 2015-04-10 12:52
I know this isn't really a duplicate because you got in first, but I didn't know how else to organise this.

**Closed as completed** 2015-04-13 10:45 UTC
Labels: duplicate
